# Generated by Django 4.2 on 2023-04-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer', models.CharField(max_length=255)),
                ('payee', models.CharField(max_length=255)),
                ('sum', models.PositiveIntegerField()),
                ('date', models.DateTimeField(verbose_name='date sent')),
                ('note', models.CharField(max_length=1023)),
            ],
        ),
    ]
