# Generated by Django 4.2 on 2023-04-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'permissions': (('add payment', 'add a new payment and edit its data, except the payer'),)},
        ),
    ]
